//Created By Meet Chavan

class StaticListData {
  //list data generated from ChatGPT
  static var cities = [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Kolhapur",
    "Thane",
    "Akola",
    "Ulhasnagar",
    "Sangli",
    "Jalgaon",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Ichalkaranji",
    "Chandrapur",
    "Parbhani",
    "Jalna",
    "Bhusawal",
    "Navi Mumbai",
    "Panvel",
    "Achalpur",
    "Beed",
    "Wardha",
    "Yavatmal",
    "Satara",
    "Washim",
    "Bhiwandi",
    "Hinganghat",
    "Ambernath",
    "Nanded",
    "Osmanabad",
    "Nandurbar",
    "Udgir",
    "Jalgaon Jamod",
    "Ausa",
    "Shegaon",
    "Lonar",
    "Gondia",
    "Baramati",
    "Barshi",
    "Pandharpur",
    "Kamthi",
    "Buldana",
    "Gondia",
    "Parli",
    "Nandura",
    "Manwath",
    "Sillod",
    "Wani",
    "Arvi",
    "Mehkar",
    "Tirora",
    "Loha",
    "Risod",
    "Shirur",
    "Savner",
    "Pusad",
    "Murtijapur",
    "Chalisgaon",
    "Wardha",
    "Gadchiroli",
    "Shrirampur",
    "Ratnagiri",
    "Kolad",
    "Chiplun",
    "Karjat",
    "Sangamner",
    "Mahad",
    "Rahuri",
    "Vaijapur",
    "Manmad",
    "Sinnar",
    "Raver",
    "Paithan",
    "Tumsar",
    "Warora",
    "Umarkhed",
    "Manor",
    "Shendurjana",
    "Sakoli",
    "Saoner",
    "Kamthi",
    "Tumsar",
    "Kalmeshwar",
    "Koradi",
    "Pulgaon",
    "Umred",
    "Narkhed",
    "Mangrulpir",
    "Chikhli",
    "Sawantwadi",
    "Amalner",
    "Chandvad",
    "Chalisgaon",
    "Chandwad",
    "Dharmabad",
    "Digras",
    "Sangola",
    "Georai",
    "Kaij",
    "Manjlegaon",
    "Partur",
    "Pathardi",
    "Rahuri",
    "Shrirampur",
    "Shrigonda",
    "Wadgaon Road",
    "Soygaon",
    "Kolhapur",
    "Ichalkaranji",
    "Kagal",
    "Miraj",
    "Panhala",
    "Uran Islampur",
    "Kudal",
    "Malwan",
    "Vengurla",
    "Akkalkot",
    "Barshi",
    "Jath",
    "Kurduvadi",
    "Mangalvedhe",
    "Pandharpur",
    "Sangola",
    "Tasgaon",
    "Vita",
    "Gadchiroli",
    "Armori",
    "Mul",
    "Aheri",
    "Kurkheda",
    "Gondpipri",
    "Desaiganj",
    "Wadsa",
    "Korchi",
    "Brahmapuri",
    "Chandrapur",
    "Chimur",
    "Ghugus",
    "Karanja",
    "Sindewahi",
    "Sawali",
    "Jawhar",
    "Mokhada",
    "Nawapur",
    "Shahada",
    "Talode",
    "Nandurbar",
    "Aheri",
    "Akot",
    "Balapur",
    "Barshitakli",
    "Chandur",
    "Chikhaldara",
    "Daryapur",
    "Karajgaon",
    "Malegaon",
    "Malkapur",
    "Mehkar",
    "Morsi",
    "Patur",
    "Telhara",
    "Varangaon",
    "Yeola",
    "Bhiwandi",
    "Kalyan",
    "Ambernath",
    "Badlapur",
    "Ulhasnagar",
    "Vasai",
    "Virar",
    "Alibag",
    "Karjat",
    "Matheran",
    "Murud",
    "Neral",
    "Palghar",
    "Pen",
    "Taloja",
    "Uran",
    "Vangani",
    "Vikramgad",
    "Wada",
    "Junnar",
    "Khed",
    "Manchar",
    "Narayangaon",
    "Rajgurunagar",
    "Shirur",
    "Baramati",
    "Daund",
    "Indapur",
    "Jejuri",
    "Karmala",
    "Morgaon",
    "Phaltan",
    "Purandhar",
    "Sasvad",
    "Sangamner",
    "Akola",
    "Akot",
    "Balapur",
    "Murtijapur",
    "Patur",
    "Telhara",
    "Washim",
    "Barsi",
    "Kurduvadi",
    "Madha",
    "Malshiras",
    "Mangalvedhe",
    "Mohol",
    "Pandharpur",
    "Sangole",
    "Solapur",
    "Tuljapur",
    "Akkalkot",
    "Barshi",
    "Karmala",
    "Madha",
    "Malshiras",
    "Mohol",
    "Pandharpur",
    "Sangole",
    "Tuljapur",
    "Ambajogai",
    "Parli",
    "Latur",
    "Ahmedpur",
    "Ausa",
    "Chakur",
    "Deoni",
    "Jalkot",
    "Nilanga",
    "Renapur",
    "Shirur-Anantpal",
    "Udgir",
    "Achalpur",
    "Amravati",
    "Anjangaon",
    "Aran",
    "Chandur",
    "Daryapur",
    "Dattapur",
    "Morshi",
    "Warud",
    "Akkalkuwa",
    "Nandurbar",
    "Nawapur",
    "Shahada",
    "Taloda",
    "Nandura",
    "Malkapur",
    "Buldana",
    "Chikhli",
    "Deulgaon Raja",
    "Khamgaon",
    "Lonar",
    "Mehkar",
    "Motala",
    "Nandura",
    "Shegaon",
    "Sindkhed Raja",
    "Sultanpur",
    "Bhayavadar",
    "Gondal",
    "Jamnagar",
    "Jetpur",
    "Mangrol",
    "Morbi",
    "Rajkot",
    "Upleta",
    "Wankaner",
    "Ankleshwar",
    "Bharuch",
    "Dahej",
    "Hansot",
    "Jambusar",
    "Palej",
    "Rajpipla",
    "Vijalpor",
    "Vilayat",
    "Dwarka",
    "Jamnagar",
    "Khambhalia",
    "Kutiyana",
    "Porbandar",
    "Upleta",
    "Bhuj",
    "Gandhidham",
    "Mandvi",
    "Abu Road",
    "Balotra",
    "Barmer",
    "Bhagirathpura",
    "Bhilwara",
    "Gandhinagar",
    "Jaipur",
    "Kishangarh",
    "Kuchaman",
    "Kuchera",
    "Mandal",
    "Merta",
    "Nagaur",
    "Nokha",
    "Osian",
    "Parbatsar",
    "Phalodi",
    "Sambhar",
    "Sujangarh",
    "Sikar",
    "Sri Madhopur",
    "Sujangarh",
    "Sardarshahr",
    "Fatehpur",
    "Churu",
    "Ratangarh",
    "Salumbar",
    "Sirohi",
    "Pali",
    "Bhinmal",
    "Jaisalmer",
    "Balotra",
    "Bharatpur",
    "Deeg",
    "Nagar",
    "Firozpur Jhirka",
    "Hodal",
    "Hansi",
    "Hisar",
    "Loharu",
    "Narnaul",
    "Pehowa",
    "Ratia",
    "Siwani",
    "Uchana",
    "Tosham",
    "Fatehabad",
    "Jakhal Mandi",
    "Jind",
    "Narwana",
    "Safidon",
    "Adampur",
    "Shahbad",
    "Sirsa",
    "Ellenabad",
    "Mandi Dabwali",
    "Nohar",
    "Bilaspur",
    "Charkhi Dadri",
    "Tohana",
    "Bhiwani",
    "Charkhi Dadri",
    "Loharu",
    "Siwani",
    "Tosham",
    "Fatehabad",
    "Gohana",
    "Jakhal Mandi",
    "Julana",
    "Pillukhera",
    "Barwala",
    "Hansi",
    "Hisar",
    "Narnaund",
    "Uklanamandi",
    "Adampur",
    "Bhuna",
    "Fatehabad",
    "Jakhal Mandi",
    "Jind",
    "Narwana",
    "Ratia",
    "Safidon",
    "Agar",
    "Alirajpur",
    "Badnawar",
    "Betma",
    "Burhanpur",
    "Depalpur",
    "Dhamnod",
    "Dhar",
    "Indore",
    "Jawar",
    "Kannod",
    "Khargone",
    "Maheshwar",
    "Mahu",
    "Manawar",
    "Mandleshwar",
    "Mhow Cantonment",
    "Nimach",
    "Pithampur",
    "Ratlam",
    "Sanawad",
    "Sarangpur",
    "Shajapur",
    "Ujjain",
    "Amarpatan",
    "Amarwara",
    "Balaghat",
    "Bemetra",
    "Bichhiya",
    "Bilaspur",
    "Bodri",
    "Chhuikhadan",
    "Dalli-Rajhara",
    "Dhamtari",
    "Dongargarh",
    "Durg",
    "Gobranawapara",
    "Jagdalpur",
    "Janjgir",
    "Kanker",
    "Kawardha",
    "Kondagaon",
    "Korba",
    "Mahasamund",
    "Mungeli",
    "Naila Janjgir",
    "Raigarh",
    "Rajnandgaon",
    "Sakti",
    "Tilda Newra",
    "Achhnera",
    "Adari",
    "Agra",
    "Aligarh",
    "Allahabad",
    "Amroha",
    "Auraiya",
    "Azamgarh",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chhibramau",
    "Chitrakoot",
    "Dadri",
    "Deoria",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddh Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur",
    "Kasganj",
    "Kaushambi",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Noida",
    "Padrauna",
    "Pilibhit",
    "Pratapgarh",
    "Rae Bareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shrawasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
    "Bulandshahr",
    "Hapur",
    "Kithor",
    "Modinagar",
    "Muradnagar",
    "Pilakhua",
    "Begusarai",
    "Bettiah",
    "Bhagalpur",
    "Bihar Sharif",
    "Bodh Gaya",
    "Buxar",
    "Chapra",
    "Darbhanga",
    "Dehri",
    "Dumraon",
    "Gaya",
    "Gopalganj",
    "Hajipur",
    "Jamalpur",
    "Jamui",
    "Kishanganj",
    "Lakhisarai",
    "Madhepura",
    "Madhubani",
    "Motihari",
    "Munger",
    "Muzaffarpur",
    "Narkatiaganj",
    "Naugachhia",
    "Nawada",
    "Purnia",
    "Rafiganj",
    "Rajgir",
    "Ramnagar",
    "Raxaul Bazar",
    "Saharsa",
    "Samastipur",
    "Sasaram",
    "Sheikhpura",
    "Sheohar",
    "Sherghati",
    "Silao",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Warisaliganj",
    "Arrah",
    "Aurangabad",
    "Bagaha",
    "Barh",
    "Barbigha",
    "Begusarai",
    "Bettiah",
    "Bhabua",
    "Bihar Sharif",
    "Buxar",
    "Chhapra",
    "Darbhanga",
    "Dehri",
    "Dumraon",
    "Gaya",
    "Gopalganj",
    "Hajipur",
    "Jamalpur",
    "Jamui",
    "Jehanabad",
    "Katihar",
    "Kishanganj",
  ];

  static var services = [
    "AC Cleaning",
    "Plumbing",
    "Electrician",
    "Carpentry",
    "Painting",
    "Landscaping",
    "Roofing",
    "Pest Control",
    "HVAC Repair",
    "Appliance Repair",
    "Flooring Installation",
    "Home Cleaning",
    "Interior Design",
    "Auto Repair",
    "Computer Repair",
    "Gardening",
    "Moving and Packing",
    "Window Cleaning",
    "Home Security",
    "Locksmith",
    "Dry Cleaning",
    "Laundry",
    "Carpet Cleaning",
    "Pool Cleaning",
    "Junk Removal",
    "Handyman Services",
    "Furniture Assembly",
    "Renovation",
    "Kitchen Remodeling",
    "Bathroom Remodeling",
    "Legal Services",
    "Financial Planning",
    "Tax Preparation",
    "Real Estate",
    "Event Planning",
    "Catering",
    "Photography",
    "Web Design",
    "Graphic Design",
    "Marketing",
    "Printing",
    "Fitness Training",
    "Personal Coaching",
    "Tutoring",
    "Childcare",
    "Pet Grooming",
    "Pet Sitting",
    "Travel Planning",
    "Wedding Planning",
    "Massage Therapy",
    "Hair Salon",
    "Nail Salon",
    "Spa Services",
    "Yoga Classes",
    "Pilates Classes",
    "Personal Training",
    "Dog Training",
    "Dog Walking",
    "Veterinary Services",
    "Plumbing Inspection",
    "Home Inspection",
    "Home Staging",
    "Home Theater Installation",
    "Security System Installation",
    "Home Automation",
    "Swimming Pool Installation",
    "Land Surveying",
    "Architectural Services",
    "House Cleaning",
    "Office Cleaning",
    "Window Installation",
    "Glass Repair",
    "Septic Tank Services",
    "Dumpster Rental",
    "Tree Services",
    "Lawn Care",
    "Irrigation Services",
    "Fence Installation",
    "Garage Door Repair",
    "Lock Installation",
    "Security Camera Installation",
    "Pressure Washing",
    "Deck Installation",
    "Concrete Services",
    "Masonry",
    "Paving",
    "Home Theater Design",
    "Audio Installation",
    "Plumbing Fixture Installation",
    "Solar Panel Installation",
    "Chimney Services",
    "Roof Repair",
    "Exterior Painting",
    "Wallpaper Installation",
    "Commercial Cleaning",
    "Event Catering",
    "Party Planning",
    "DJ Services",
    "Music Lessons",
    "Language Lessons"
  ];
}
